### ISSUE TITLE
[meta] Finalize the project

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/faunanet#24]
**What's the overarching idea and why is this additional feature necessary?**
This is the core element of Sparrow that binds all the individual parts together. As such, it does not include much new functionality itself, but provides the interface and framework in which they interact. A few elements are still missing and need to be created first. 

**Describe into what individual steps/features your suggestion decays, and outline their basic ideas in one sentence each**
- [x] add some `source` abstraction class that separates technical details from what is done with the data. This is responsible for watching the folder where raw data lands in for example #23 
- [x] add a wrapper for the core functionality. This would essentially be something that calls `SparrowRecording`.  
    - [x] Directorywatcher from `birdnetlib`
    - ~~maybe add batch analyzer if the package should be used as a standalone system.~~
- [x] add an element that abstracts away outward communication technicalities
- [ ] dockerize the project #27 
- [x] add packaging #47 
- [x] add installation routine
- [x] add documentation #44 
- [x] add cli/ repl #41 
- [x] add coverage report #26 
- [x] converge to a way for custom model integration #14 
- [x] add model exchange to watcher  #34 
- [x] rename everything to `faunanet` #46 
- [x] #36

**Comment by iulusoy** [comment]
Same here, I would have something like a `watch_folder_out` to abstract away the technical specificity from the core functionality.
